// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const offlineAwareFetch: typeof fetch = (input, init) => {
  if (typeof navigator !== "undefined" && !navigator.onLine) {
    return Promise.reject(new Error("No internet connection"));
  }

  return fetch(input, init);
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: offlineAwareFetch,
  },
});

if (typeof window !== "undefined") {
  const syncAutoRefreshState = () => {
    if (navigator.onLine) {
      supabase.auth.startAutoRefresh();
      return;
    }

    supabase.auth.stopAutoRefresh();
  };

  syncAutoRefreshState();
  window.addEventListener("online", syncAutoRefreshState);
  window.addEventListener("offline", syncAutoRefreshState);
}
